### ISSUE TITLE
openlibm enablement for PPC64

### ISSUE THREAD

**Issue by edelsohn** [JuliaLang/openlibm#113]
Add support to allow openlibm to configure, build and provide basic functionality on PPC64 Linux big endian and little endian.

Are there any known issues preventing PPC support or configuration support has not been enabled?

**Comment by ViralBShah** [comment]
Someone would have to provide the patches. I don't know if the generic C implementation is good enough to be fully portable yet.

**Comment by edelsohn** [comment]
My understanding is openlibm works with a few missing pieces backported from FreeBSD. PPC64 Linux little endian is transitioning to IEEE128 long double, so the port can focus on that and fall back to 64 bit long double when necessary.

How could we work with the community to accomplish this?

**Comment by StefanKarpinski** [comment]
If you have PPC hardware, try building openlibm on it and see how it goes. If there are problems, report them and/or try to fix them. If you get stuck and it's possible to give people here access to the PPC hardware for debugging, then perhaps we can help with that too.

**Comment by edelsohn** [comment]
Free access to Power8 systems running PPC64 Linux is available for Open Source developers through OSUOSL Powerdev, FIT Brno, Unicamp, SuperVessel and other resources.

As I mentioned earlier, an initial test seemed to show a couple of missing bits and work-arounds necessary for long double.

I am trying to gauge if anyone in the openlibm community would be interested in sponsorship to address the basic enablement issues.

**Comment by StefanKarpinski** [comment]
I'm not sure what you mean by "sponsorship".

**Comment by edelsohn** [comment]
Sponsorship = a financial bounty through Bountysource.com for implementing basic functionality on PPC64 Linux.

**Comment by StefanKarpinski** [comment]
If you can muster up a decent amount of money for this work I'm sure it will help make it happen.
