### ISSUE TITLE
Tag a new release - 0.5

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/openlibm#117]
With the ppc support, I think we should tag a new release - 0.5. Is there anything else we need to do before we tag?

**Comment by tkelman** [comment]
We should probably run julia's tests against it on a variety of platforms.

**Comment by ViralBShah** [comment]
What's the best way to do so? The changes here are minor and there are no api changes - so I think this is pretty safe.

**Comment by StefanKarpinski** [comment]
Is it likely that there will be and API changes in the future? If not, then a 1.0 release may be warranted. Bugfixes would go into 1.0.x releases; new exported functions would go in 1.x releases, and any breaking API changes (including deleting exported functions) would require a 2.0 release.

**Comment by tkelman** [comment]
> What's the best way to do so?

Prepare the PR that changes the `openlibm.version` and checksum files first, run it through CI before doing the tag here?

> Is it likely that there will be and API changes in the future?

Not necessarily API changes, but in terms of code #108 will be pretty big and still needs some cleanup. I also think we should look carefully at what musl has done with their libm since they started from pretty much the same code bases we did, but have been better at maintaining and pulling in bug fixes.

**Comment by ViralBShah** [comment]
Can you point to the musl implementation? The issue we have faced is that we never automated the migration from msun. It needs a bunch of sed scripts really, and unfortunately I didn't save that in #108. I'll have to do it once more carefully.

**Comment by ViralBShah** [comment]
By definition, there should be no major API changes, since the goal is to be a libm replacement. I would like to sort out #108 and keeping up with msun before tagging 1.0.

**Comment by tkelman** [comment]
http://git.musl-libc.org/cgit/musl/tree/src/math - looks like they don't have powerpc support at the moment though

**Comment by ViralBShah** [comment]
That code looks quite clean! Do they maintain a record of what all they pull in from msun and how frequently?

**Comment by tkelman** [comment]
http://git.musl-libc.org/cgit/musl/log/src/math

**Comment by ViralBShah** [comment]
I meant tracking the msun logs. Looks like it started from msun, but has significantly changed, and ongoing fixes are manually tracked. I'll try this out to see if there is merit in following musl instead of msun before refreshing msun.

**Comment by ViralBShah** [comment]
Detailed notes on the musl approach - http://nsz.repo.hu/libm/ 

Many functions have been completely rewritten in musl.

**Comment by tkelman** [comment]
The numpy maintainers have also brought up bionic's libm, used on android: https://github.com/android/platform_bionic/tree/master/libm

**Comment by ViralBShah** [comment]
Bionic looks nice in that it does closely follow msun.

**Comment by ViralBShah** [comment]
I think at the very least, we should follow the bionic model here, and maintain a set of patches external to msun that we need in openlibm. With that we can be 1.0.

I love what the musl guys have done, but need to check with them on long term maintenance plans and understand the community momentum, before we adopt that as the way forward. What Szabolcs Nagy has done there, is what I wanted to do with openlibm in the first place, but he's done really amazing stuff.

**Comment by nalimilan** [comment]
I've just checked that building a RPM works with GCC6, and that's OK. But tests fail on i686:
```
+ make -C test test-float
make: Entering directory '/builddir/build/BUILD/openlibm-master/test'
gcc  -O2   test-float.c -D__BSD_VISIBLE -I ../include -I../src -L.. -lopenlibm -Wl,-rpath=/builddir/build/BUILD/openlibm-master -o test-float
../libopenlibm.so: undefined reference to `fpsetprec'
../libopenlibm.so: undefined reference to `fpgetprec'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'test-float' failed
```

test-float used to pass on i686, though test-double failed. (Tests also fail on ARMv7 but that was already the case with 0.4.)

Also, do we actually need to bump the SOVERSION to 2? Did the API really break?

**Comment by ViralBShah** [comment]
I did not bump the SOVERSION here, but I do believe it was required when we removed some APIs.

I think the test failure on ARM is now a couple of minor things.

**Comment by tkelman** [comment]
the undefined references also occurred on win32 appveyor for the test pr, and win64 errored due to incorrect dllexport

**Comment by ViralBShah** [comment]
@tkelman Could you turn on appveyor? I logged into appveyor and authorized it to access openlibm and kicked off a build? But, I guess we need an appveyor.yml file and some other things to be done to turn this on for every commit and PR?

**Comment by ViralBShah** [comment]
The i686 build is fixed. Can you try again? Should work on windows too, but would be nice to setup appveyor.

**Comment by tkelman** [comment]
There isn't currently a template for doing source builds with gcc on appveyor, it takes a fair bit of work to obtain the right toolchain and run from within msys2 or cygwin, it's not a 5-minute thing.

**Comment by ViralBShah** [comment]
Ok. Then I think this is good to tag for now, and we can make further releases as we find issues.

**Comment by tkelman** [comment]
For now there should be an option to "only build when appveyor.yml is present" that you can turn on to avoid the red status until we figure that out.

**Comment by ViralBShah** [comment]
I checked `Skip branches without appveyor.yml`

**Comment by tkelman** [comment]
You can rebase https://github.com/JuliaLang/julia/pull/15212 for now to see if it works on Windows within Julia's build system - I think there are still dllexport problems that need to be fixed before tagging. AppVeyor here standalone would have to look like a cut-down version of Julia's appveyor setup, which is kind of complicated. I actually am not sure whether openlibm's makefiles work properly if you try to build them on Windows by themselves, outside of Julia's build system.

**Comment by tkelman** [comment]
At least locally it's working on win32 but failing on win64, see the appveyor log from that PR for the dllexport-related error. Bisect points to 8b3b52067563a5a212a7fbacf360907fe2dc5e57 as being the first bad commit.

**Comment by ViralBShah** [comment]
I merged #118 and verified that all tests pass on 32-bit and 64-bit linux, as well as OS-X is the same level of tests passing as before. On ARM 32-bit, which used to hang/crash, the test suite now runs completely, with a few FP exception errors. If win32 and win64 are looking good, I think this is a go for 0.5.

**Comment by nalimilan** [comment]
Wait for a bit, I'm running the build.

**Comment by nalimilan** [comment]
Looks good, thanks! Also good to see ARM tests closer to passing completely.

If you want a perfect release, you can have a look at these warnings:
```
gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fno-gnu89-inline -std=c99 -Wall -I/builddir/build/BUILD/openlibm-master -I/builddir/build/BUILD/openlibm-master/include -I/builddir/build/BUILD/openlibm-master/ld80 -I/builddir/build/BUILD/openlibm-master/amd64 -I/builddir/build/BUILD/openlibm-master/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -fPIC -c ld80/s_exp2l.c -o ld80/s_exp2l.c.o
In file included from ld80/s_exp2l.c:33:0:
/builddir/build/BUILD/openlibm-master/amd64/bsd_cdefs.h:129:0: warning: "__P" redefined
 #define __P(protos) protos  /* full-blown ANSI C */
 
In file included from /usr/include/features.h:368:0,
                 from /usr/include/stdio.h:27,
                 from /builddir/build/BUILD/openlibm-master/src/cdefs-compat.h:12,
                 from ld80/s_exp2l.c:27:
/usr/include/sys/cdefs.h:82:0: note: this is the location of the previous definition
 #define __P(args) args
 
In file included from ld80/s_exp2l.c:33:0:
/builddir/build/BUILD/openlibm-master/amd64/bsd_cdefs.h:131:0: warning: "__CONCAT" redefined
 #define __CONCAT(x,y) __CONCAT1(x,y)
 
In file included from /usr/include/features.h:368:0,
                 from /usr/include/stdio.h:27,
                 from /builddir/build/BUILD/openlibm-master/src/cdefs-compat.h:12,
                 from ld80/s_exp2l.c:27:
/usr/include/sys/cdefs.h:88:0: note: this is the location of the previous definition
 #define __CONCAT(x,y) x ## y
 
In file included from ld80/s_exp2l.c:33:0:
/builddir/build/BUILD/openlibm-master/amd64/bsd_cdefs.h:230:0: warning: "__always_inline" redefined
 #define __always_inline __attribute__((__always_inline__))
 
In file included from /usr/include/features.h:368:0,
                 from /usr/include/stdio.h:27,
                 from /builddir/build/BUILD/openlibm-master/src/cdefs-compat.h:12,
                 from ld80/s_exp2l.c:27:
/usr/include/sys/cdefs.h:307:0: note: this is the location of the previous definition
 # define __always_inline __inline __attribute__ ((__always_inline__))
 
In file included from ld80/s_exp2l.c:33:0:
/builddir/build/BUILD/openlibm-master/amd64/bsd_cdefs.h:242:0: warning: "__nonnull" redefined
 #define __nonnull(x) __attribute__((__nonnull__(x)))
 
In file included from /usr/include/features.h:368:0,
                 from /usr/include/stdio.h:27,
                 from /builddir/build/BUILD/openlibm-master/src/cdefs-compat.h:12,
                 from ld80/s_exp2l.c:27:
/usr/include/sys/cdefs.h:285:0: note: this is the location of the previous definition
 # define __nonnull(params) __attribute__ ((__nonnull__ params))
 
In file included from ld80/s_exp2l.c:33:0:
/builddir/build/BUILD/openlibm-master/amd64/bsd_cdefs.h:361:0: warning: "__strong_reference" redefined
 #define __strong_reference(sym,aliassym) \
 
In file included from ld80/s_exp2l.c:27:0:
/builddir/build/BUILD/openlibm-master/src/cdefs-compat.h:28:0: note: this is the location of the previous definition
 #define __strong_reference(sym,aliassym) \
 
In file included from /builddir/build/BUILD/openlibm-master/src/math_private.h:23:0,
                 from ld80/s_exp2l.c:38:
/builddir/build/BUILD/openlibm-master/src/types-compat.h:10:0: warning: "__pure2" redefined
 #define __pure2
 
In file included from ld80/s_exp2l.c:33:0:
/builddir/build/BUILD/openlibm-master/amd64/bsd_cdefs.h:203:0: note: this is the location of the previous definition
 #define __pure2  __attribute__((__const__))

```
https://kojipkgs.fedoraproject.org//work/tasks/9161/13149161/build.log

**Comment by nalimilan** [comment]
What, the tests pass on PPC64LE? *That*'s news!

Being greedy, I should note that similar warnings appear there:
```
gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8 -fno-gnu89-inline -std=c99 -Wall -I/builddir/build/BUILD/openlibm-master -I/builddir/build/BUILD/openlibm-master/include -I/builddir/build/BUILD/openlibm-master/ld80 -I/builddir/build/BUILD/openlibm-master/powerpc -I/builddir/build/BUILD/openlibm-master/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -fPIC -c src/s_log1pf.c -o src/s_log1pf.c.o
In file included from src/math_private.h:24:0,
                 from src/s_lrint.c:32,
                 from src/s_llrint.c:9:
src/fpmath.h:47:0: warning: "_LITTLE_ENDIAN" redefined
 #define _LITTLE_ENDIAN    __ORDER_LITTLE_ENDIAN__
 
<built-in>: note: this is the location of the previous definition
In file included from src/math_private.h:24:0,
                 from src/s_lround.c:33,
                 from src/s_llround.c:11:
src/fpmath.h:47:0: warning: "_LITTLE_ENDIAN" redefined
 #define _LITTLE_ENDIAN    __ORDER_LITTLE_ENDIAN__
 
<built-in>: note: this is the location of the previous definition
In file included from src/math_private.h:24:0,
                 from src/s_lrint.c:32,
                 from src/s_llrintf.c:9:
src/fpmath.h:47:0: warning: "_LITTLE_ENDIAN" redefined
 #define _LITTLE_ENDIAN    __ORDER_LITTLE_ENDIAN__
 
<built-in>: note: this is the location of the previous definition
```

**Comment by simonbyrne** [comment]
> What, the tests pass on PPC64LE?

Oh, you missed all the fun yesterday...

**Comment by simonbyrne** [comment]
If you know how to get rid of the redef warnings, I'd be grateful.

**Comment by nalimilan** [comment]
> Oh, you missed all the fun yesterday...

Hehe, I was actually going though my e-mail starting from the most recent. Not a the most logical way...

> If you know how to get rid of the redef warnings, I'd be grateful.

I hadn't realized it was system-dependent. Actually, that's because my `/usr/include/sys/cdefs.h` defines `_SYS_CDEFS_H`, and openlibm checks for `_SYS_CDEFS_H_`. We should probably check for both, right?

**Comment by nalimilan** [comment]
As regards warnings  on PPC, this is because recent gcc versions provide `_LITTLE_ENDIAN` and `_BIG_ENDIAN` built-in macros. Looks like we simply need an `#ifndef`.

**Comment by ViralBShah** [comment]
I have a patch shortly.

**Comment by nalimilan** [comment]
Actually I was also looking into it. We'll be able to compare our changes.

**Comment by ViralBShah** [comment]
This should do it - I think.

````
 #ifdef __APPLE__
 #include "../i387/osx_asm.h"
 #define CNAME(x) EXT(x)
 #else
-#include "bsd_cdefs.h"
+//#include "bsd_cdefs.h"
+#include "<sys/cdefs.h>"
````

**Comment by nalimilan** [comment]
But  will that work on all platforms? Why keep `bsd_cdefs.h` at all then?

**Comment by ViralBShah** [comment]
That's the question I have. If it works on linux and windows, we can get rid of bsd_cdefs.h

**Comment by nalimilan** [comment]
Looks like it works if I get rid of all occurrences of `bsd_cdefs.h`. How can we test Windows? And would it work on Mac OS X?

**Comment by nalimilan** [comment]
See my `nl/includes` branch. It gets rid of warnings, but it fails on x86:
```
make[1]: Entering directory '/builddir/build/BUILD/openlibm-master/test'
gcc  -O2   test-double.c -D__BSD_VISIBLE -I ../include -I../src -L.. -lopenlibm -Wl,-rpath=/builddir/build/BUILD/openlibm-master -o test-double
../libopenlibm.so: undefined reference to `__fpgetprec'
collect2: error: ld returned 1 exit status
```
https://kojipkgs.fedoraproject.org//work/tasks/9885/13149885/build.log

**Comment by nalimilan** [comment]
Regarding `_LITTLE_ENDIAN` and `_BIG_ENDIAN`, the problem is that when gcc defines them, they are boolean flags, while openlibm uses them to store an integer pattern. Could we remove the underscore, or add an `OPENLIBM_` prefix? Anyway, these are used in only two or three files.

**Comment by nalimilan** [comment]
BTW, if somebody wants to put a bounty on the first openlibm distribution package supporting PPC... :-) OK, I'm cheating a bit.

**Comment by ViralBShah** [comment]
Either fix is fine on the ENDIAN flags. This should fix the issue I was facing with `vs/msun` too. I think it is best to add the `OPENLIBM_` prefix.

**Comment by EdSchouten** [comment]
2016-02-27 17:38 GMT+01:00 Milan Bouchet-Valat <notifications@github.com>:
> Regarding _LITTLE_ENDIAN and _BIG_ENDIAN, the problem is that when gcc defines them, they are boolean flags, while openlibm uses them to store an integer pattern. Could we remove the underscore, or add an OPENLIBM_ prefix? Anyway, these are used in only two or three files.

I think the preferred way of testing the endianness is to use
__BYTE_ORDER__ and __ORDER_LITTLE_ENDIAN__/__ORDER_BIG_ENDIAN__. These
also hold integer patterns:

$ cc -dM -E - < /dev/null | grep ORDER
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412

-- 
Ed Schouten <ed@nuxi.nl>
Nuxi, 's-Hertogenbosch, the Netherlands
KvK-nr.: 62051717

**Comment by ViralBShah** [comment]
Would be great if you could submit a PR!

**Comment by nalimilan** [comment]
I've made a PR at https://github.com/JuliaLang/openlibm/pull/125. Indeed, I now think the cleanest solution is to use the gcc/clang macros, and define them when they aren't. That way, the code is easy to read for anybody familiar with these compilers.

**Comment by ViralBShah** [comment]
I think we are good to tag 0.5 now.

**Comment by simonbyrne** [comment]
sounds good to me

**Comment by nalimilan** [comment]
Sorry, looks like I missed another warning with `__pure2`. I've made a new (smaller) PR: https://github.com/JuliaLang/openlibm/pull/126

**Comment by nalimilan** [comment]
BTW, there are still a few warnings with GCC6. I've looked at them, and they don't seem to reflect actual bugs. They don't need to be fixed for the release, but it might be good to have a look at some point so that we can spot more easily really problematic ones.
- on x86_64: https://kojipkgs.fedoraproject.org//work/tasks/4861/13214861/build.log
- on ARM: https://kojipkgs.fedoraproject.org//work/tasks/4860/13214860/build.log

**Comment by ViralBShah** [comment]
Tagged v0.5.

**Comment by nalimilan** [comment]
Could you call it 0.5.0 instead? We'll probably have 0.5.1 after this rather than 0.6.

**Comment by nalimilan** [comment]
Same for openspecfun. I've prepared draft releases.

**Comment by ViralBShah** [comment]
Good point. I may take a few hours to get to it, but if it is easy enough, can you edit it on github?

**Comment by nalimilan** [comment]
Sure, I just did it. You'll have to update your PR https://github.com/JuliaLang/julia/pull/15212 though.

**Comment by ViralBShah** [comment]
Done.
