### ISSUE TITLE
Move to JuliaMath

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/openlibm#144]
I suggest moving openlibm to JuliaMath.

**Comment by ViralBShah** [comment]
Cc @simonbyrne @tkelman

**Comment by tkelman** [comment]
same as https://github.com/JuliaLang/openspecfun/issues/47#issuecomment-242325026

> I don't want to do this one as much as pure-Julia packages because old versions of Julia hardcoded the url in the build system.

**Comment by ararslan** [comment]
Maybe what we could do is to move the repository to JuliaMath but keep a frozen fork of it in JuliaLang. That way ongoing development can happen in JuliaMath, which will use JuliaMath's CI queue, and old versions of Julia will still point to a valid repository but it will no longer be updated. Does that seem reasonable?

**Comment by ViralBShah** [comment]
I am ok with that. Same for openspecfun (if it is still in julialang).

**Comment by ararslan** [comment]
Okay, if you want to do that you're one of the few with the necessary permissions to do so (ownership in both JuliaLang and JuliaMath).
