### ISSUE TITLE
ARM build failed on Debian during testing

### ISSUE THREAD

**Issue by Deni90** [JuliaLang/openlibm#147]
Build failed on test-double with following error on ARM:

> test/test-double
> testing double (without inline functions)
> Failure: acos (inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: acos (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: acos (1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: acos (-1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: asin (inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: asin (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: asin (1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: asin (-1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: cos (inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: cos (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: sin (inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: sin (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: sincos (inf, &sin_res, &cos_res) puts NaN in sin_res plus invalid exception: Exception "Invalid operation" not set
> Failure: sincos (-inf, &sin_res, &cos_res) puts NaN in sin_res plus invalid exception: Exception "Invalid operation" not set
> Failure: tan (inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: tan (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: acosh (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: acosh (-1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: atanh (1) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: atanh (-1) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: atanh (1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: atanh (-1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: Test: expm1 (1) == M_El - 1.0
> Result:
>  is:          1.71828182845904531284e+00   0x1.b7e151628aed30000000p+0
>  should be:   1.71828182845904509080e+00   0x1.b7e151628aed20000000p+0
>  difference:  2.22044604925031308085e-16   0x1.00000000000000000000p-52
>  ulp       :  1.0000
>  max.ulp   :  0.0000
> Maximal error of `expm1'
>  is      :  1.0000 ulp
>  accepted:  0.0000 ulp
> Failure: log (0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log (-0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log (-1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: log10 (0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log10 (-0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log10 (-1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: log1p (-1) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log1p (-2) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: log2 (0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log2 (-0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: log2 (-1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: logb (0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: logb (-0) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (-0.1, 1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: pow (-0.1, -1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: pow (-10.1, 1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: pow (-10.1, -1.1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: pow (0, -1) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (0, -11) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (-0, -1) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (-0, -11) == -inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (0, -2) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (0, -11.1) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (-0, -2) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: pow (-0, -11.1) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: sqrt (-1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: sqrt (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: gamma (0) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: gamma (-3) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: lgamma (0) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: lgamma (-3) == inf plus division by zero exception: Exception "Divide by zero" not set
> Failure: tgamma (0) == inf plus divide-by-zero: Exception "Divide by zero" not set
> Failure: tgamma (-0) == inf plus divide-by-zero: Exception "Divide by zero" not set
> Failure: tgamma (-2) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: tgamma (-inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fmod (inf, 3) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fmod (-inf, 3) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fmod (3, 0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fmod (3, -0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remainder (1, 0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remainder (1, -0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remainder (inf, 1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remainder (-inf, 1) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remquo (1, 0, &x) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remquo (1, -0, &x) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remquo (inf, 1, &x) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: remquo (-inf, 1, &x) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (inf, 0.0, 1.0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (-inf, 0.0, 1.0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (0.0, inf, 1.0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (0.0, -inf, 1.0) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (inf, inf, -inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (-inf, inf, inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (inf, -inf, inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: fma (-inf, -inf, -inf) == NaN plus invalid exception: Exception "Invalid operation" not set
> Failure: y0 (-1.0) == NaN: Exception "Invalid operation" not set
> Failure: y0 (0.0) == -inf: Exception "Divide by zero" not set
> Failure: y1 (-1.0) == NaN: Exception "Invalid operation" not set
> Failure: y1 (0.0) == -inf: Exception "Divide by zero" not set
> Failure: yn (0, -1.0) == NaN: Exception "Invalid operation" not set
> Failure: yn (0, 0.0) == -inf: Exception "Divide by zero" not set
> Failure: yn (1, -1.0) == NaN: Exception "Invalid operation" not set
> Failure: yn (1, 0.0) == -inf: Exception "Divide by zero" not set
> 
> Test suite completed:
>   1118 test cases plus 932 tests for exception flags executed.
>   87 errors occurred.
> Makefile:49: recipe for target 'test' failed
> make[1]: **\* [test] Error 1

Full log:
https://buildd.debian.org/status/fetch.php?pkg=openlibm&arch=armel&ver=0.5.3%2Bdfsg-1&stamp=1471055021

It seems issue #83 didn't fix the test failures on Debian because openlibm failed with and without the dcc0d8d commit.
dcc0d8d is included in 0.5.0+dfsg-1 version, but in 0.5.0+dfsg-2 is removed (Changelog: \* Fix missing buildflags, enable optimization again for *int.c and *intf.c.)

**Comment by ginggs** [comment]
This should be fixed by PR:#151
