### ISSUE TITLE
Windows Build (?)

### ISSUE THREAD

**Issue by evolvedmicrobe** [JuliaLang/openlibm#149]
This looks like a great project, and I had a few questions about the windows build.

The README indicates this can build on windows, but also that it needs GCC, which does not come  installed with windows by default, and so most windows users get a GCC version by installing either MinGW or Cygwin.

Although MinGW is often used, it does not contain the uname utility, which the Makefile calls right away.  Does this mean that the windows builds to date have been on cygwin and this is an expected prerequisite?  Has anyone ever built this on windows with just MinGW?

**Comment by nalimilan** [comment]
Cc: @tkelman

**Comment by tkelman** [comment]
"mingw" as just a compiler is pretty much obsolete and not so useful without a full make, bash, coreutils environment. openlibm can be built in msys2 or cygwin, most often using the mingw target (cross) compilers. the posix target msys2 or cygwin compilers probably work too but don't get tested that often.

**Comment by evolvedmicrobe** [comment]
Thanks for the quick response.  Looks like the dependencies pretty much mirror the ones for building Julia on windows then.

https://github.com/JuliaLang/julia/blob/master/README.windows.md

**Comment by tkelman** [comment]
Yeah, in terms of the recommended build environment setup that's the best place to look. You won't need absolutely everything that Julia needs to just build openlibm, but close enough.
