### ISSUE TITLE
Mips support patch

### ISSUE THREAD

**Issue by rbirdic** [JuliaLang/openlibm#153]
Hi,
I submited in Debian a patch to support mips architectures:
https://bugs.debian.org/852441
I adapted changes to latest openlibm version.
Patch has been tested on my local machines for mips, mipsel and mips64el.
Here is pull request:
https://github.com/JuliaLang/openlibm/pull/152

**Comment by CDLuminate** [comment]
New PR based on #152  https://github.com/JuliaLang/openlibm/pull/181
