### ISSUE TITLE
Error: invalid character '(' in mnemonic

### ISSUE THREAD

**Issue by pragmascript** [JuliaLang/openlibm#154]
I am trying to compile ba43b3616c59bdce38bb1138dbb507b73b2148a4 on windows with gcc 4.9.2 under cygwin and get the following error:
```bash
gcc   -m32 -march=i686 -m32 -I/cygdrive/c/users/pragma/downloads/openlibm/openlibm -I/cygdrive/c/users/pragma/downloads/openlibm/openlibm/include -I/cygdrive/c/users/pragma/downloads/openlibm/openlibm/i387 -I/cygdrive/c/users/pragma/downloads/openlibm/openlibm/src -DASSEMBLER -D__BSD_VISIBLE -I/cygdrive/c/users/pragma/downloads/openlibm/openlibm/ld80 -c i387/e_exp.S -o i387/e_exp.S.o
i387/e_exp.S: Assembler messages:
i387/e_exp.S:11: Error: invalid character '(' in mnemonic
i387/e_exp.S:69: Error: invalid character '(' in mnemonic
Make.inc:144: recipe for target 'i387/e_exp.S.o' failed
make: *** [i387/e_exp.S.o] Error 1
```

Edit:
I also tried now with mingw and gcc 6.3.0 but get a similar error.
```bash
gcc   -m64 -m64 -I/c/Users/pragma/Downloads/openlibm/openlibm -I/c/Users/pragma/Downloads/openlibm/openlibm/include -I/c/Users/pragma/Downloads/openlibm/openlibm/amd64 -I/c/Users/pragma/Downloads/openlibm/openlibm/src -DASSEMBLER -D__BSD_VISIBLE -I/c/Users/pragma/Downloads/openlibm/openlibm/ld80 -c amd64/e_remainder.S -o amd64/e_remainder.S.o
amd64/e_remainder.S: Assembler messages:
amd64/e_remainder.S:12: Error: invalid character '(' in mnemonic
make: *** [Make.inc:144: amd64/e_remainder.S.o] Fehler 1
```

**Comment by vtjnash** [comment]
I don't think anyone has attempted to support the Cygwin environment. (Cygwin binaries are incompatible with Mingw64 due to ABI differences). The build is known to work using the mingw64 cross compiler. The mingw project is very antiquated now and is known to not generate correct code or support the latest assembly targets.

**Comment by pragmascript** [comment]
Hey thanks my mingw build was based on https://github.com/msys2.
which uses the latest gcc version 6.3.
I also tried using clang but got errors there as well.
I will try again with mingw64

**Comment by vtjnash** [comment]
IIRC, the gcc in msys2 is a fork of Cygwin, not mingw64

**Comment by pragmascript** [comment]
I am not sure but it sais MinGW-w64 on http://www.msys2.org/. I will try with MinGW-w64 directly.

**Comment by tkelman** [comment]
check the target with `gcc -dumpmachine` to be sure of which environment you're running msys2 in (msys2 native which is cygwin-style, vs mingw64)

**Comment by pragmascript** [comment]
thanks for your help i managed to build it with a seperate mingw64 install
