### ISSUE TITLE
aarch64 build is missing frexpl() and related long double functions

### ISSUE THREAD

**Issue by mato** [JuliaLang/openlibm#157]
When building openlibm (latest master with #151) on aarch64, the "long double" functions (`frexpl()` and friends) are not built.

I have a (perhaps naive) fix at https://github.com/mato/ocaml-freestanding/commit/9e1d25addb280a2e58f879cf9efacc4e172e56f9.

/cc @staticfloat

**Comment by staticfloat** [comment]
This seems reasonable, @yuyichao do we just avoid calling these long double functions on `aarch64` and that's why we don't have issues with missing symbols?

**Comment by yuyichao** [comment]
We never use these functions anywhere.

`long double` should be [IEEE 754-2008 qual precision on aarch64](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0055b/IHI0055B_aapcs64.pdf) so it should be correct to enable these.

**Comment by mato** [comment]
Shall I open a PR with the change in https://github.com/mato/ocaml-freestanding/commit/9e1d25addb280a2e58f879cf9efacc4e172e56f9?

**Comment by staticfloat** [comment]
Yes please.

**Comment by mato** [comment]
Fixed by #158.
