### ISSUE TITLE
Hack that makes tests to fail on Mac OS: anomaly or expected behaviour?

### ISSUE THREAD

**Issue by stanislaw** [JuliaLang/openlibm#166]
Hello,

I am seeing a weird issue which I don't understand: this branch [acos-issue](https://github.com/JuliaLang/openlibm/compare/master...stanislaw:acos-issue) produces the following output:

```
$ make test
...
Test suite completed:
  1118 test cases plus 932 tests for exception flags executed.
  13 errors occurred.
```

given I create identical copy of `__ieee754_acos` function so that this copy's name is not transformed to `acos` by a preprocessor like this happens with original `__ieee754_acos`. Please follow my comment on `libm-test.c` file in my branch. If I enable its prototype declaration in libm-test.c` file - tests are passing, if I don't the tests are failing.

I am not a C expert so maybe I am missing some trivial knowledge like that I am hitting some sort of undefined behaviour here.

----

One example:

```
Failure: Test: acos (-1) == pi
Result:
 is:          1.68430090000000000000e+08   0x1.41414140000000000000p+27
 should be:   3.14159265358979311600e+00   0x1.921fb54442d180000000p+1
 difference:  1.68430086858407348394e+08   0x1.414140db7812b0000000p+27
 ulp       :  379270838206751804751872.0000
 max.ulp   :  0.0000
```

----

My clang version is:

```
$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks.

**Comment by staticfloat** [comment]
I'm willing to bet this is due to https://github.com/JuliaLang/openlibm/pull/164.  In essence, our test suite has been incredibly flawed by some clever compilers replacing calls to `acos()` with their own version because we haven't been passing in the `-fno-builtin` flag.  We'll fix this before the new release, and hopefully that will fix this issue.

**Comment by stanislaw** [comment]
This sounds like a good explanation of this behaviour. I didn't know about `-fno-builtins` flag until your comment in #164. However I am still seeing this issue on my branch even though I have added `-fno-builtin` flag as it is added in [your commit](https://github.com/JuliaLang/openlibm/pull/164/commits/400407ea4092b5ef27e3c5b666b053524b25f621).

----

For your interest there is another report inspired by openlibm bu this time related to LLVM, that I have opened on llvm.org for clang versions: 3.9, 4.0, 5.0:

[Possible bug: LTO, LLVM 5.0.0, mac OS: certain calls get shadowed by functions from system library given -flto flag provided and do not otherwise ](https://bugs.llvm.org/show_bug.cgi?id=34645).

**Comment by staticfloat** [comment]
@stanislaw can you verify for me that the latest `master` still fails your test?

**Comment by stanislaw** [comment]
@staticfloat, I have just verified it. Yes, it is still failing.

I would suggest you to check my branch out. The weird part is that presence of a prototype, uncommented or commented, makes the tests pass or fail.

**Comment by stanislaw** [comment]
This is my `clang`:

```
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by stanislaw** [comment]
@staticfloat I believe this issue is not the issue of openlibm even though it can cause all kinds of bugs coming from shadowing.

I have reduced the number of tests, left only 1 test and checked the assembly with and without function declaration (again, see the [diff between my branch and latest master](https://github.com/JuliaLang/openlibm/compare/master...stanislaw:acos-issue) again).

The difference boils down to the following:

without prototype enabled (commented out):

```
declare i32 @__no_shadow__ieee754_a_cos(...) 
```

vs

with prototype disabled:

```
declare double @__no_shadow__ieee754_a_cos(double)
```

and hence the calls are respectively:

```
  %2 = call i32 (i32, ...) bitcast (i32 (...)* @__no_shadow__ieee754_a_cos to i32 (i32, ...)*)(i32 0) #4	
```

and 

```
  %2 = call double @__no_shadow__ieee754_a_cos(double 0.000000e+00) #4
```

so the tests are failing because of `double -> i32` truncation.

See the full diff here: https://www.diffchecker.com/kq7GlmCs

----

So the confusing part is that compiler *allows compilation without a function prototype declaration but in this case it puts a placeholder "declaration with i32*.

I am not sure if this is a bug or expected behavior.

**Comment by staticfloat** [comment]
This sounds like the expected behavior of the "implicit int" rule in C89.  I would think the compiler would complain about a lack of a declaration though.  See [this SO link](https://stackoverflow.com/questions/8220463/c-function-calls-understanding-the-implicit-int-rule) for more.

**Comment by stanislaw** [comment]
@staticfloat thank you very much for the explanation. This definitely explains the issue! I was running `make test` before the -fno-builtin flag fix and I saw some of the calls were getting shadowed. I had to create a copy of `acos` and give it a different name to make sure my function would be run without any substitutions and this is how I found this prototype issue. I am happily closing this!

**Comment by stanislaw** [comment]
> I would think the compiler would complain about a lack of a declaration though.

Isn't this what missing prototype `-Wmissing-prototypes` warning is for?

**Comment by staticfloat** [comment]
Excellent, I'm glad we were able to get to the bottom of this.

> Isn't this what missing prototype -Wmissing-prototypes warning is for?

Yes, I dare say that does seem reasonable.  :)
