### ISSUE TITLE
openlibm and libm: mutation testing

### ISSUE THREAD

**Issue by stanislaw** [JuliaLang/openlibm#172]
Hello,

I am addressing developers and maintainers of both libm and openlibm.

I will start with tl;dr part first.

I am a developer of mutation testing system called [Mull](https://github.com/mull-project/mull).

Our development involves analysis of open source projects. This analysis helps us to develop Mull further and also we learn more about how various projects are tested in the wild.

I have recorded a small demo from my sessions. It is about libm which I was able to compile on Ubuntu 64 bit Docker image and it is very similar to what I am also doing with openlibm on macOS.

[Analyzing sqrt function from libm C library with Mull](https://www.youtube.com/watch?v=_ipprdCdVHc&t=9s&list=PLmo9Xl8PKe5sfM4gTYSUVaxJCJdQ06hDP&index=1)

---

Some time ago I started to analyze [openlibm](https://github.com/JuliaLang/openlibm/issues/new) and [libm](https://sourceware.org/newlib/libm.html). I was specifically looking for something with lots of computational code, so libm and then openlibm turned out to be very good targets for my testing of so-called "math mutation operators", "scalar value mutation operators", "replace function call mutation operators" etc.

Based on my analysis **both openlibm and libm have a lack of mutation testing coverage**: you can modify chunks of the functions like `acos` or `sqrt` and still see all of the tests passing.

These are my observations about the code:

- The code in both libraries seems use `__ieee754_*` functions that have
`Copyright (C) 1993 by Sun Microsystems` on it.
- `libm/test/**` has much more tests compared to `openlibm`. For example `acos` is tested against ~280 test cases. They are passing on my machine with some tweaks even though the test suite is not maintained since 2002.
- `openlibm/test` suite works out of the box on macOS but has very few tests.
- Our `Mull` gives roughly `50-60%` mutation coverage on functions like `acos` or `sqrt` which means that both `libm` and `openlibm` are actually not tested well enough.

There are a few things I would like to ask:

1) Looks like both libraries have the same origin but the code in both is very different these days. What is the reason of this difference in implementations and what is the criteria of deciding which one performs better after the years?

2) libm uses a struct to convert double to a pair of two uint32_t's and back.

```c
typedef union __ieee_double_shape_type {
  double value;
  ...
  struct {
    uint32_t lsw;
    uint32_t msw;
  } parts;
  ...
} __ieee_double_shape_type;
```

And it uses these pairs to write the test cases like:

```
{64,13, 37,__LINE__, 0x40500000, 0x00000000, 0xbff33333, 0x33333333},			/* 64.0000=f(-1.20000)*/
```

Where `0x40500000, 0x00000000` is expected result and `0xbff33333, 0x33333333` is the argument.

Why `libm` does this? Why not work with `double` directly? And if this is a good practice, why then `openlibm` does not follow this approach?

3) Are libm and openlibm known to be used in critical software? I am wondering how do people prove the correctness of how both libraries work given:
- `libm`'s tests are not maintained since 2002. Its test coverage of ~280 cases for each function seems good but even a first shot with Mull reveals that there is lot of weird code that does not contribute to the implementation **if we judge only using that test suite**.
- `openlibm` compiles and runs its tests nicely right from master but has so few of them so it is quite hard to consider its test suite as one that gives a confidence.

4) Our long-term plans for Mull include making an open-source service for mutation testing of OSS projects like [google/oss-fuzz](https://github.com/google/oss-fuzz). Does anybody see the potential in libm/openlibm being tested against mutation coverage metric like [oss-fuzz projects](https://github.com/google/oss-fuzz/tree/master/projects) are tested using fuzzers?

Thanks for attention.

**Comment by simonbyrne** [comment]
Hi @stanislaw,

1. Firstly, "libm" is the generic name for C math library (typically covering the functions defined in `math.h`): openlibm is a particular implementation (based on code from the FreeBSD libm). Many implementations (including this one) are based on the libm written by Sun (sometimes referred to as "msun"), which was publicly released as [fdlibm](http://www.netlib.org/fdlibm/). Most libm's are built as part of C standard libraries (libc): the other one you link to is part of [newlib](https://sourceware.org/newlib/).

2. My guess is that the newlib-libm uses type-punning to ensure exact bit reproducibility of the inputs and outputs. This is typically not necessary these days, since `strtod` functions are fairly reliable at giving correctly rounded conversions from decimal to binary, and C99 introduced hex float literals which are guaranteed to be exact, but I guess that they weren't satisfied with this. Note that type-punning does have the downside of not being transportable across different-endian systems.

3. openlibm is maintained specifically for use in [Julia](https://julialang.org/), though there may be other users. I can't say about newlib-libm. I concede that the tests in openlibm are probably lacking, but we generally rely on the fact that the code has a long an proven history, and is also fairly well tested in downstream projects like Julia itself.

4. While it would be nice to have better tests, we are in the process of moving most of the math functionality into Julia itself, so it is likely that openlibm will not continue to be maintained by us in the long term (though we would certainly be happy for someone else to take it over).

**Comment by kargl** [comment]
Stanslaw,

It is unclear to me what MULL is meant to do with respect to 
the math library.  Usually, the approximations used to compute
a function in libm are fairly well vetted.  If you change the 
algorithm, then it is only logical that testing will be worse
than for the untouched code.

In addition to Simon's observations, I have few comments.

1. Are you sure you are testing what you think you are?  The
   build commands fly by too fast in the video to see the
   compiler options.  Most modern compilers will use a hardware
   sqrt instruction.  The function is specified by IEEE 754 to
   give the correct result with at most 0.5 ULP error, and both
   hardware and software implementations can achieve this error.
   On my i686-*-freebsd system, I have

   % cat a.c
   #include <math.h>
   double
   foo(double x)
   {
      double y;
      y = sqrt(x);
      return y;
   }
   % clang -S -O2 -c a.c && grep sqrt a.s
        fsqrt
   % clang -S -O2 -c -fno-builtin a.c && grep sqrt a.s
        calll   sqrt
   .LBB0_2:                             # %call.sqrt
        jmp     sqrt                    # TAILCALL

   fsqrt is the Intel FPU instruction.  sqrt would be a call
   to the library function.

2. For math functions of a single float variable, it is possible
   to exhaustively test the float version of the math functions.
   For the higher precisions of double and long double it not 
   feasible to do exhaustive testing.  You probably need to speak
   with whomever chose the values you find in a testsuite for his
   or her reason for those values.  The first question is "do
   these values sample all intervals of the domain that x may be 
   split?"   for example, if there are no subnormal numbers and 
   MULL only changes the section of code that involves subnormal
   numbers, then all tests will pass.  The second question is "do
   these values contain any samples near the ends of the intervals?"
   It is likely that the function is approximated by a polynomial,
   and polynomial approximation typically have the largest error
   near end points.  See below for testing of erff() and erf()

3. The splitting of a double into 2 32-bit is useful for a few 
   reasons.  First, operations on integers are typically much faster
   than using floating point.  Second, operations involving integer
   will not raise spurious floating point exceptions.  Consider the
   zeroth order Bessel function, j0(x) -> 1 for x -> 0.  If one uses
   j0 = 1 - x * x / 4, then an underflow exception may be raised for
   small finite x whereas j0 = 1 clearly doesn't underflow.  In fact,
   you may find tests of the form: "if (ix < 0xSomeMask) j0 = 1 - tiny;" 
   where ix is an integer and tiny is some (volatile) double that causes
   the floating point inexact exception to be raised.  (FreeBSD's libm
   uses a sligthly different to raise inexact.)

4. Getting back to testing the functions.  Here's my testing of erff()
   with program testf and erf() with program testd.  Note a different
   method of computation is used in each interval.  It would be 
   impractical to include these in a testsuite unless one is willing 
   to wait a long time.

   % ./testf -e                     <-- Test exceptional values
   erff(0.000000) = 0.000000, (expecting 0)
   erff(-0.000000) = -0.000000, (expecting -0)
   erff(inf) = 1.000000, (expecting 1)
   erff(-inf) = -1.000000, (expecting -1)
   erff(nan) = nan, (expecting nan)
   % ./testf -s                     <-- Test for speed in intervals
   [0.0000e+00, 8.4375e-01], 1000000 calls, 0.017240 secs, 0.01724 usecs/call
   [8.4375e-01, 1.2500e+00], 1000000 calls, 0.016108 secs, 0.01611 usecs/call
   [1.2500e+00, 2.8572e+00], 1000000 calls, 0.074287 secs, 0.07429 usecs/call
   [2.8572e+00, 5.0000e+00], 1000000 calls, 0.044557 secs, 0.04456 usecs/call
   % time ./testf -E double         <-- Exhaustive testing in the intervals
                                    <-- Reference solution is erf()
   Interval tested: [0,0.8438]
   ULP: 0.88991,   x =  8.36538494e-01f, /* 0x3f562763 */
   flt =  7.63208270e-01f, /* 0x3f43619e */
   dbl =  7.6320832311588460e-01, /* 0x3fe86c33, 0xdc7a2ace */
   Interval tested: [0.8438,1.25]
   ULP: 0.74680,   x =  1.24691188e+00f, /* 0x3f9f9acf */
   flt =  9.22166944e-01f, /* 0x3f6c1322 */
   dbl =  9.2216689903762872e-01, /* 0x3fed8264, 0x281a404d */
   Interval tested: [1.25,2.857]
   ULP: 0.73838,   x =  1.26933289e+00f, /* 0x3fa27980 */
   flt =  9.27363515e-01f, /* 0x3f6d67b2 */
   dbl =  9.2736347088951443e-01, /* 0x3fedacf6, 0x285f3766 */
   Interval tested: [2.857,5]
   ULP: 0.50006,   x =  2.86012173e+00f, /* 0x40370c3c */
   flt =  9.99947667e-01f, /* 0x3f7ffc92 */
   dbl =  9.9994763731586533e-01, /* 0x3fefff92, 0x2fff7dd6 */
      112.78 real       112.72 user         0.00 sys

   % ./testd -e
   erf(0.000000) = 0.000000 (expecting 0)
   erf(-0.000000) = -0.000000 (expecting -0)
   erf(inf) = 1.000000 (expecting 1)
   erf(-inf) = -1.000000 (expecting -1)
   erf(nan) = nan (expecting nan)
   % ./testd -s
   [0.0000e+00, 8.4375e-01], 1000000 calls, 0.026560 secs, 0.02656 usecs/call
   [8.4375e-01, 1.2500e+00], 1000000 calls, 0.030467 secs, 0.03047 usecs/call
   [1.2500e+00, 2.8571e+00], 1000000 calls, 0.240845 secs, 0.24084 usecs/call
   [2.8571e+00, 7.0000e+00], 1000000 calls, 0.180954 secs, 0.18095 usecs/call
   % time ./testd -n 10          <-- Test 10 million values in each interval
                                 <-- Reference solution is from MPFR
   % time ./testd -n 10
   Interval tested: [0.0000e+00,8.4375e-01]
   ULP: 0.95460, x =  1.3643776364377637e-02, /* 0x3f8bf144, 0xaa3b44c1 */
   Interval tested: [8.4375e-01,1.2500e+00]
   ULP: 0.78098, x =  1.2279657290465729e+00, /* 0x3ff3a5bf, 0x646dd23d */
   Interval tested: [1.2500e+00,2.8571e+00]
   ULP: 0.71098, x =  1.2532692648569266e+00, /* 0x3ff40d64, 0x129a4786 */
   Interval tested: [2.8571e+00,7.0000e+00]
   ULP: 0.50005, x =  2.8928613705711368e+00, /* 0x40072494, 0x8093b7d9 */
     3867.00 real      3811.28 user         0.13 sys

**Comment by stanislaw** [comment]
@simonbyrne @kargl thank you very much for the answers, I am learning a lot from
them. Let me answer to you both in one comment to not fork this thread.

For your interest this is the answer I got on newlib mailing list:

[Re: openlibm and libm: mutation testing](https://sourceware.org/ml/newlib/2017/msg01125.html)

---

> 1. Firstly, "libm" is the generic name for C math library...

Thanks, this helps to understand the genealogy.

> 2. My guess is that the newlib-libm uses type-punning to ensure exact bit
reproducibility of the inputs and outputs. This is typically not necessary these
days, since strtod functions are fairly reliable...

Thanks for the explanation, I didn't know about type punning before. And yes,
using a trial and error method I had to
[change the order of lsw and msw in the struct, in the union](https://github.com/stanislaw/libm/commit/48dd50b094bc40913ec798f81c59aafe60564872#diff-d7cc3cc67680a613efe30127148a102bR35)
to make it work on Docker Ubuntu (I created and them modified a copy of their
union type declaration). One thing I didn't understand: why did you mention
`strtod` - what do strings have to do with type punning through union:
`double` <-> `uint32_t`? How are strings in game here?

> 3. openlibm is maintained specifically for use in Julia...

Got it. Speaking of math, do you mean [these](https://github.com/JuliaLang/julia/blob/master/test/math.jl) tests or something else?

> 4. While it would be nice to have better tests, we are in the process of
moving most of the math functionality into Julia itself...

Got it. No comments.

---

> 1. Are you sure you are testing what you think you are?

I think I am. I am aware of the functions like `acos` or `sqrt`
[getting shadowed by compiler builtin functions, openlibm#164](https://github.com/JuliaLang/openlibm/pull/164)
or, like you mentioned, hardware functions.

I am using `-O0 -g` flags because they are the best for Mull to give me a
feedback I can process easier: the code is not optimized so it is very natural
to tweak it in IDE and see the mutations that correspond to unoptimized code.

Additionally I verified that libm's functions like `__ieee754_acos`
and `__ieee754_sqrt` are indeed called (printfs are not on video but had been
there before I recorded).

> 2. For math functions of a single float variable...

Unfortunately I don't know yet what polynomial approximation means, but your
answer looks similar to the answer from newlib's thread above: Mull found
the code chunks which do not contribute significantly to the final result. I
wish I knew more about this domain, I will try to understand it better.

> 3. The splitting of a double into 2 32-bit is useful for a few
reasons. First, operations on integers are typically much faster
than using floating point. Second, operations involving integer
will not raise spurious floating point exceptions. Consider the
zeroth order Bessel function, j0(x) -> 1 for x -> 0. If one uses
j0 = 1 - x * x / 4, then an underflow exception may be raised for
small finite x whereas j0 = 1 clearly doesn't underflow. In fact,
you may find tests of the form: "if (ix < 0xSomeMask) j0 = 1 - tiny;"
where ix is an integer and tiny is some (volatile) double that causes
the floating point inexact exception to be raised. (FreeBSD's libm
uses a sligthly different to raise inexact.)

The point about speed is clear, the point floating point exceptions is not but
I will record it as something I should learn more about.

> 4. Getting back to testing the functions. Here's my testing of erff()
with program testf and erf() with program testd. Note a different
method of computation is used in each interval. It would be
impractical to include these in a testsuite unless one is willing
to wait a long time.

This seems clear enough.

---

Unfortunately I don't have much time to analyze newlib/libm and openlibm
further so I quickly tried libFuzzer and KLEE to compare the results of Mull
with the results produced by these tools.

These are results of `sqrt` function from newlib/libm:

1) Both KLEE and libFuzzer found the overshift error:

```
sqrt_ieee.c:41:33: runtime error: shift exponent 32 is too large for 32-bit type 'uint32_t' (aka 'unsigned int')
```

Mull shows lots of survived mutations in the branch where overshift `32 - i`
happens:

```c
...
#ifdef __STDC__
double __ieee754_sqrt(double x)
#else
double __ieee754_sqrt(x) double x;
#endif
{
  ...
  /* normalize x */
  m = (ix0 >> 20);
  if (m == 0) { /* subnormal x */
    while (ix0 == 0) {
      m -= 21;
      ix0 |= (ix1 >> 11);
      ix1 <<= 21;
    }
    for (i = 0; (ix0 & 0x00100000) == 0; i++)
      ix0 <<= 1;
    m -= i - 1;
    ix0 |= (ix1 >> (32 - i));
    ix1 <<= i;
  }
  ...
```

I took the test where KLEE found overshift, added it to the testsuite, ran Mull
again and saw that many mutations in this branch were killed so I observed
a correlation between what Mull showed as a branch with a poor coverage and the
location in which KLEE detected as overshift.

2) libFuzzer found another problem: `left shift of negative value`

```
sqrt_ieee.c:112:13: runtime error: left shift of negative value -531
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior sqrt_ieee.c:112:13 in
```

```c
#ifdef __STDC__
double __ieee754_sqrt(double x)
#else
double __ieee754_sqrt(x) double x;
#endif
{
  ...
  ix1 = q1 >> 1;
  if ((q & 1) == 1)
    ix1 |= sign;
  ix0 += (m << 20); // left shift of negative value
  INSERT_WORDS(z, ix0, ix1);
  return z;
}
```

For this location Mull reported that all mutations were killed which means
that there is a test which is masking the problem. This is very valuable finding
that shows me and my colleague that masking is a very important factor that
determines how successful is Mull in showing weak code.

3) libFuzzer thinks that the following is a runtime error:

`sqrt_ieee.c:25:22: runtime error: division by zero`

though this code is apparently a code designed by its authors, there is no
mistake:

```c
  return (x - x) / (x - x); / sqrt(-ve) = sNaN /
```

---

Let me quote myself again:

> Our development involves analysis of open source projects. This analysis helps
us to develop Mull further and also we learn more about how various projects are
tested in the wild.

If anyone is interested in mutation testing analysis for their C or C++ project,
please let me know.

@kargl, by the way, one of my next steps is to check how Mull runs on
FreeBSD. I could try to analyze any project on that system as part of my
work on FreeBSD support. Let me know if you could recommend me a project with a
good test suite that I could run Mull on.

Thanks for attention.

**Comment by simonbyrne** [comment]
> One thing I didn't understand: why did you mention
> `strtod` - what do strings have to do with type punning through union:
> `double` <-> `uint32_t`? How are strings in game here?

To ensure that the numeric literal in the C code is correctly handled by the compiler, e.g. the literal `-1.2` is correctly converted to the `double` with bit-pattern `0xbff3_3333_3333_3333`. 

> Speaking of math, do you mean [these](https://github.com/JuliaLang/julia/blob/master/test/math.jl) tests or something else?

Yes.
