### ISSUE TITLE
Build failure on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/openlibm#18]
Openlibm fails to build on powerpc and arm. Failure is in compiling s_fma.c.

https://buildd.debian.org/status/package.php?p=julia&suite=sid

**Comment by ViralBShah** [comment]
@talex5 Is it fair to close this that openlibm works on ARM? @nalimilan reported some errors, but that URL is no longer valid. I suggest opening a new issue for specific breakages.

**Comment by talex5** [comment]
@ViralBShah It build on ARM (and seems to work), but there are some failures in the unit tests, as reported above, so you might want to open a new issue for that. You can see the errors just by enabling the ARM tests in the Travis script and pushing to a new branch so it runs them.

**Comment by ViralBShah** [comment]
Good idea. Best to have a separate issue for various failing tests on different architectures and compilers.
