### ISSUE TITLE
No real support for cross compiling

### ISSUE THREAD

**Issue by scialex** [JuliaLang/openlibm#89]
Cross compiling this is an enormous pain. It should be easier. Currently if I want to cross compile to i386 I need to run: `make LDFLAGS="-m32 -march=i386" SFLAGS="-m32 -march=i386" CFLAGS="-m32 -march=i386" ARCH=i386` which is really stupid.

**Comment by kmsquire** [comment]
Any chance you can put together a pull request that would address this?

**Comment by scialex** [comment]
maybe. I'll take a look at it. at the moment I am working on some other stuff.
