### ISSUE TITLE
Update to the latest updates from msun

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/openlibm#91]
There are a bunch of accumulated updates on msun, which we need to pull into openlibm. I suspect many of these will also get us much closer to passing tests on mac, as they improve clang support.

https://github.com/freebsd/freebsd/tree/master/lib/msun

**Comment by tkelman** [comment]
same as #101

**Comment by ViralBShah** [comment]
Thanks. I guess #101 also identifies the point of divergence, so good to have that one open.
