### ISSUE TITLE
Website downloads point to git master instead of releases

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/openlibm#92]
I've just noticed you set up http://julialang.org/openlibm/. That's cool, but when you click on "Download ZIP" or "Download TAR", you get the latest git master, which is not the common expectation. People who want the development version will use git. Better provide the latest stable release.

Also, providing both ZIP and TAR is a bit confusing without more explanations. Maybe say "source ZIP/TAR"?

**Comment by ViralBShah** [comment]
It is whatever github provided. We should have downloads for releases.
