### ISSUE TITLE
Build on Raspberry Pi 2 fails ( ARM )

### ISSUE THREAD

**Issue by stochasticForest** [JuliaLang/openlibm#94]
Downloaded and tried to make the latest version of openlibm, as part of the install process for Julia, the build failed with the following error:

```
s_cargl.c:(.text+0x0): multiple definition of `carg'
src/s_carg.c.o:s_carg.c:(.text+0x0): first defined here
src/s_cpowl.c.o: In function `cpow':
s_cpowl.c:(.text+0x0): multiple definition of `cpow'
src/s_cpow.c.o:s_cpow.c:(.text+0x0): first defined here
src/s_cimagl.c.o: In function `cimag':
s_cimagl.c:(.text+0x0): multiple definition of `cimag'
src/s_cimag.c.o:s_cimag.c:(.text+0x0): first defined here
src/s_conjl.c.o: In function `conj':
s_conjl.c:(.text+0x0): multiple definition of `conj'
src/s_conj.c.o:s_conj.c:(.text+0x0): first defined here
src/s_creall.c.o: In function `creal':
s_creall.c:(.text+0x0): multiple definition of `creal'
src/s_creal.c.o:s_creal.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Makefile:35: recipe for target 'libopenlibm.so' failed
make: *** [libopenlibm.so] Error 1
```

Should this library have been pulled in automatically as part of the Julia build process?
'make julia' failed with the following error:

```
 collect2: error: ld returned 1 exit status
Makefile:35: recipe for target 'libopenlibm.so' failed
make[2]: *** [libopenlibm.so] Error 1
Makefile:790: recipe for target 'openlibm/libopenlibm.so' failed
make[1]: *** [openlibm/libopenlibm.so] Error 2
Makefile:60: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

It was this error which lead me to try to install openlibm manually. 

The operating system is Raspbian.

How can I help resolve this ?

cheers :)

**Comment by pao** [comment]
Julia's `Make.arm` currently specifies `USE_SYSTEM_LIBM=1`, so it looks like that's an acceptable solution that will get you through a build.

I'm not sure if that means there's still an independent issue with openlibm; I'll leave this issue open for now.

**Comment by nalimilan** [comment]
You could try with this PR: https://github.com/JuliaLang/openlibm/pull/86

**Comment by stochasticForest** [comment]
Yes, the Make.arm currently has USE_SYSTEM_LIBM=1 set, that didn't seem to resolve the problem with building julia, I wonder if I"m missing a dependency that I should have installed ?

**Comment by nalimilan** [comment]
Have you edited Make.user and added `include $(JULIAHOME)/Make.arm`? Then it shouldn't try to build openlibm. Cf. https://github.com/JuliaLang/julia/blob/master/README.arm.md

**Comment by stochasticForest** [comment]
Yes I have a Make.user with that contents in the julia directory. :)

**Comment by ViralBShah** [comment]
I mistakenly wiped out my crouton setup. Will see where this is when I get it working again.

**Comment by stochasticForest** [comment]
Thank you very much.

Is there any diagnostic information I could provide that might help you ?

**Comment by kwende** [comment]
I'm coming to this party late, but I'm wondering if there has been a resolution made for this? I just tried building julia on my RP2 and got the following (which is what brought me here): 

s_cargl.c:(.text+0x0): multiple definition of `carg'
src/s_carg.c.o:s_carg.c:(.text+0x0): first defined here
src/s_cpowl.c.o: In function `cpow':
s_cpowl.c:(.text+0x0): multiple definition of `cpow'
src/s_cpow.c.o:s_cpow.c:(.text+0x0): first defined here
src/s_cimagl.c.o: In function `cimag':
s_cimagl.c:(.text+0x0): multiple definition of `cimag'
src/s_cimag.c.o:s_cimag.c:(.text+0x0): first defined here
src/s_conjl.c.o: In function `conj':
s_conjl.c:(.text+0x0): multiple definition of `conj'
src/s_conj.c.o:s_conj.c:(.text+0x0): first defined here
src/s_creall.c.o: In function `creal':
s_creall.c:(.text+0x0): multiple definition of `creal'
src/s_creal.c.o:s_creal.c:(.text+0x0): first defined here
collect2: ld returned 1 exit status
Makefile:35: recipe for target 'libopenlibm.so' failed
make[2]: *** [libopenlibm.so] Error 1
Makefile:844: recipe for target 'openlibm/libopenlibm.so' failed
make[1]: *** [openlibm/libopenlibm.so] Error 2
Makefile:51: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2

**Comment by ViralBShah** [comment]
I believe the latest master should build correctly, at least.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
