### ISSUE TITLE
openlibm - aarch64 (arm 64) support

### ISSUE THREAD

**Issue by virendra-pathak** [JuliaLang/openlibm#95]
Hi Openlibm group,

I am trying to compile (with gcc) openlibm (http://openlibm.org/) on a arm juno board (armv-8 aarch64) with Fedora 21 (with linux kernel).
But the compilation fails with following error:
make
Makefile:18: aarch64/Make.files: No such file or directory
make: *** No rule to make target 'aarch64/Make.files'.  Stop.

Few Question w.r.t openlibm
1) Is openlibm supports aarch64 (armv8-a) architecture? If yes, please share the compilation steps.
2) I see a arm directory inside openlibm but not aarch64. Is this arm directory is for armv7 and below architecture ?
3) If aarch64 support is not present, please give some insight on porting effort required ? What are the key areas in the library where works needs to be done?

<machine details where I am trying to compile openlibm for aarch64>
uname -a
Linux juno 3.10.55.0-1-linaro-lt-vexpress64 #1ubuntu1~ci+141022094025 SMP Wed Oct 22 09:41:06 UTC 2014 aarch64 aarch64 aarch64 GNU/Linux

gcc (Linaro GCC 5.1-2015.06-1~dev) 5.1.1 20150608

openlibm top commit id
commit 3ee2a6e6a9fc68cbf2ab00f830b9059215e40b06
Merge pull request #68 from talex5/type_includes 
[RFC] Don't use sys/types.h

Thanks- 
Virendra Kumar Pathak

**Comment by ViralBShah** [comment]
I don't think anyone has tried this before yet. If FreeBSD has an implementation, we could try that. Or if the existing arm support can be made to work for aarch64, that could be an option as well.

**Comment by EdSchouten** [comment]
Pull request #100 already provides some of the source changes that are necessary to support this.

**Comment by ViralBShah** [comment]
Closed by #100
