### ISSUE TITLE
IEEE 754 compatiblity

### ISSUE THREAD

**Issue by alexchandel** [JuliaLang/openlibm#96]
Does this library conform to IEEE 754, insofar as the instructions it uses do? If so, could this be noted (prominently) in the readme?

**Comment by tkelman** [comment]
That's the goal, if there are counterexamples that haven't been reported yet it would be good to know about them. I'm not sure we've found a thorough enough 754 compliance test to claim in bold letters that we pass every single piece of the standard, but adding more tests and finding any places where the implementations could still use work would be great.

**Comment by StefanKarpinski** [comment]
Do other libm implementations typically assert IEEE 754 compliance?

**Comment by simonbyrne** [comment]
It depends how you define "IEEE 754 compliant". If you mean "implements everything recommended", then no (not even CRLibm has provably correctly rounded `pow` function). Some of the functionality (notably exceptions and rounding control) depends on the compiler (and, AFAIK, no C compiler strictly handles these correctly).

Even if you define it as all the mandatory "shall" functions, then there are a couple of things missing (`roundToIntegralTiesToEven` and `totalOrder` are both missing: these were added in the C TR1 2014 as `roundeven` and `totalorder` but aren't widely implemented yet).

**Comment by ViralBShah** [comment]
I think @simonbyrne's reply above answers the question posed. I don't think we need to mention this in the README.
